server:
  port: 9000
spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          proxy-client-oidc:
            provider: authserver
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: proxy-client-oidc
        provider:
          authserver:
            issuer-uri: ${AUTH_SERVER_URI:http://localhost:8000}
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO