server:
  port: 8000
spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: pass
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security: TRACE