server:
  port: 8000
spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: pass
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security: TRACE
  pattern:
    console: "[%X{requestId}] %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"